trigger:
  branches:
    include:
    - main

variables:
  - group: ServiceNow

stages:

  - stage: Build
    displayName: 'Build da Aplicação'
    jobs:
      - job: Job
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - task: CmdLine@2
            displayName: 'npm install and build'
            inputs:
              script: |
                npm install
                npm run build

  - stage: CreateChange
    displayName: 'Criar Change no ServiceNow'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: OpenChange
        displayName: 'Abrir Change Request'
        pool:
          name: Server
        steps:
          - task: ServiceNow-DevOps-Server-Change-Acceleration@1
            displayName: 'Criar e Aguardar Aprovação do Change'
            inputs:
              connectedServiceName: "suzanodev-Teste Final ServiceNow-ServiceNow DevOps Service Connection"
              changeRequestDetails: |
                {
                  "attributes": {
                    "requested_by": {
                      "name": "Pedro Lucas Sousa Moura"
                    },
                    "assignment_group": {
                      "name": "Servicenow Support"
                    },
                    "priority": "2",
                    "comments": "This is a sample pipeline script to be added in your change step",
                    "work_notes": "Update this to work_notes",
                    "start_date": "2023-09-07 11:59:59",
                    "end_date": "2023-09-09 11:59:59"
                  }
                }

  - stage: Deploy
    displayName: 'Deploy da Aplicação'
    dependsOn: CreateChange
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: 'Executar Deploy'
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: CmdLine@2
            displayName: 'Executar Deploy'
            inputs:
              script: |
                echo "Iniciando deploy da branch $(Build.SourceBranchName)"
                echo "Build ID: $(Build.BuildId)"